### ISSUE TITLE
Inverted noise on negative values

### ISSUE THREAD

**Issue by vnenkpet** [andrewrk/node-perlin-noise#1]
Intersection between positive and negative coordinates appears mirrored as opposed to continuous which is troublesome for certain use-cases.

Great work so far btw!

**Comment by andrewrk** [comment]
ah interesting. I haven't touched the code in a while - want to make a pull request?

**Comment by vnenkpet** [comment]
Welp, I actually put this issue on a wrong repo. Had more implementations opened, sorry xD Yours is probably ok.
